ESP8266Audio_COMMIT := 46b36574ed27544e1dd15daa204f1eb484e9a840

download-libs:
	wget https://github.com/earlephilhower/ESP8266Audio/raw/$(ESP8266Audio_COMMIT)/src/libtinysoundfont/tsf.h  -O include/tsf.h
